// <auto-generated />
using DoDucTue190.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoDucTue190.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240106065738_Create_Student")]
    partial class Create_Student
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DoDucTue190.Models.Student", b =>
                {
                    b.Property<string>("StudentName")
                        .HasColumnType("TEXT");

                    b.Property<double>("StudentAge")
                        .HasColumnType("REAL");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentName");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
